name: ai4pfas
channels:
- rdkit
- conda-forge
- pytorch
dependencies:
- pip
- rdkit
- numpy
- ipython
- jupyter
- matplotlib
- numpy
- pandas
- scipy
- scikit-learn
- pytorch
- autograd
- pip:
  - gpflow
  - torch-geometric
  - tensorflow=2.3
  - tensorflow-probability=0.11.1